spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8003
spring:
  profiles:
    active: dev
  application:
    name: service001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://94.191.27.166:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.test.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true

---
server:
  port: 8003
spring:
  profiles:
    active: prod
  application:
    name: service001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://94.191.27.166:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.test.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true

